Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 50
Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
Layout/LineLength:
  Exclude:
    - '**/*_spec.rb'
AllCops:
  SuggestExtensions: false
  Exclude:
    - 'lib/swagger/**/*'
    - 'db/schema.rb'