services:
  api:
    build: .
    container_name: "invoice-api"
    hostname: "invoice-api"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
  database:
    image: postgres:15
    container_name: "invoice-db"
    hostname: "invoice-db"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - 8000:8080
    environment:
      - SWAGGER_JSON_URL=http://localhost:3000/swaggers
volumes:
  db_data: