services:
  api:
    build: .
    container_name: "invoice-api"
    hostname: "invoice-api"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env
  database:
    image: postgres:15
    container_name: "invoice-db"
    hostname: "invoice-db"
    ports:
      - "5432:5432"
    env_file:
      - .env